---
title: "Génération 2017"
output: pdf_document
date: "`r format(Sys.time(), '%e %B %Y')`"
params:
  reactive_graph_situation_apres_3_ans: 'NULL'
  reactive_plot_repartition_par_profession: 'NULL'
  reactive_plot_repartition_par_secteur: 'NULL'
  reactive_tx_en_emploi: 'NULL'
  reactive_tx_chomage: 'NULL'
  reactive_tx_en_edi: 'NULL'
  reactive_tx_a_tps_partiel: 'NULL'
  reactive_revenu_median: 'NULL'
  reactive_tx_jugent_coherent: 'NULL'
  reactive_tx_estiment_ss_employes: 'NULL'
---


```{r echo=FALSE}
params[["reactive_graph_situation_apres_3_ans"]]
```

```{r echo=FALSE}
params[["reactive_plot_repartition_par_profession"]]
```

```{r echo=FALSE}
params[["reactive_plot_repartition_par_secteur"]]
```

```{r echo=FALSE}
params[["reactive_tx_en_emploi"]]
```

```{r echo=FALSE}
params[["reactive_tx_chomage"]]
```

```{r echo=FALSE}
params[["reactive_tx_en_edi"]]
```

```{r echo=FALSE}
params[["reactive_tx_a_tps_partiel"]]
```

```{r echo=FALSE}
params[["reactive_revenu_median"]]
```

```{r echo=FALSE}
params[["reactive_tx_jugent_coherent"]]
```

```{r echo=FALSE}
params[["reactive_tx_estiment_ss_employes"]]
```